apiVersion: openshift.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: cloud-native-workshop
spec:
  user: 
    number: 10
    password: openshift
  source:
    gitURL: https://github.com/mcouliba/cloud-native-workshop
    gitBranch: "ocp4.5"
  infrastructure:
    argocd:
      enabled: true
      operatorHub:
        channel: alpha
        clusterServiceVersion: argocd-operator.v0.0.12
    bookbag:
      enabled: true
      image:
        name: quay.io/mcouliba/cloud-native-workshop-bookbag
        tag: "ocp4.5"
    codeReadyWorkspace:
      enabled: true
      operatorHub:
        channel: latest
        clusterServiceVersion: crwoperator.v2.2.0
      openshiftOAuth: false
      pluginRegistryImage:
        name: quay.io/mcouliba/che-plugin-registry
        tag: "2.2.0.GA_v2"
    etherpad:
      enabled: true
    gitea:
      enabled: true
      image:
        name: quay.io/gpte-devops-automation/gitea-operator
        tag: v0.17
    nexus:
      enabled: true
    pipeline:
      enabled: true
      operatorHub:
        channel: ocp-4.4
        clusterServiceVersion: openshift-pipelines-operator.v1.0.1
    project:
      enabled: true
      devName: dev-project
      stagingName: cn-project
    serviceMesh:
      enabled: true
      serviceMeshOperatorHub:
        channel: "stable"
        clusterServiceVersion: servicemeshoperator.v1.1.5
      elasticSearchOperatorHub:
        channel: "4.5"
      jaegerOperatorHub:
        channel: "stable"
      kialiOperatorHub:
        channel: "stable"
        clusterServiceVersion: kiali-operator.v1.12.13
    istioWorkspace:
      enabled: false
      image:
        name: quay.io/maistra/istio-workspace
        tag: v0.0.3
    vault:
      enabled: false
      image:
        name: vault
        tag: "1.3.3"
      agentInjectorImage:
        name: "hashicorp/vault-k8s"
        tag: "0.3.0"
    workshopper:
      enabled: false
